export const fieldTooltips = {
  problem_statement: "State the painful problem in the customer's words. Avoid describing your solution here.",
  target_customer_persona: "Describe the person or team with this problem: buyer, user, company type, and situation.",
  urgency: "How urgent is this for them right now?",
  pain: "How painful is the problem if they do nothing?",
  frequency: "How often does this problem show up in their workflow?",
  willingness_to_pay: "How likely are they to spend money to fix this problem?",
  customer_discovery_count: "How many real customer interviews or discovery calls have you completed?",
  key_insight: "The sharpest thing you have learned that most people do not know yet.",
  falsifiable_hypothesis: "Name the evidence that would prove this opportunity is real or not real.",
  tam_m: "A rough estimate of the total market size in millions of dollars.",
  sam_m: "The part of the market you can realistically reach with your go-to-market.",
  som_m: "The slice you could realistically win in the next few years.",
  growth_rate_pct: "Annual growth rate of the total market.",
  market_type: "New markets create new spend, existing markets take share, re-segmented markets change positioning, and clone markets copy a proven model into a new geography or niche.",
  timing_signals: "Macro trends, regulatory shifts, buyer behavior changes, or technology unlocks that make now the right time.",
  competitors: "Who else solves this problem, how dangerous are they, and why do you win?",
  pricing_model: "How you charge customers: subscription, usage, transaction fee, services, hybrid, or another model.",
  acv: "Average contract value per customer. Use a realistic annual estimate.",
  moat_network: "Does the product become more valuable when more people use it? Slack is weak alone, strong with a team.",
  moat_data: "Do you collect data that competitors cannot easily copy?",
  moat_switching: "How hard would it be for customers to leave for a competitor?",
  moat_scale: "Does the business get meaningfully stronger or cheaper to run as it grows?",
  moat_brand: "Would customers trust or choose you because of the brand?",
  moat_ip: "Do you own defensible IP, trade secrets, regulatory approvals, or patents?",
  moat_summary: "Explain the primary moat in one paragraph. Be specific about why it compounds.",
  time_to_copy: "How long before a well-funded competitor can replicate the core product or go-to-market advantage?",
  risk_label: "The specific thing that could kill or materially weaken this opportunity.",
  risk_category: "The area of the business this risk threatens most.",
  heat_level: "Overall severity of the risk right now.",
  risk_likelihood: "How likely this risk is to happen.",
  risk_impact: "How damaging this risk would be if it happens.",
  mitigation_note: "The concrete action that reduces this risk.",
  risk_owner: "The person responsible for watching and reducing this risk.",
  risk_status: "Whether this risk is still open, being worked, or already mitigated.",
  phase: "0->1 validates the problem, 1->10 builds a repeatable motion, 10->100 scales what already works.",
  kpi_primary: "The one metric that shows whether this opportunity is winning right now.",
  kpi_revenue: "The money-related metric that proves customers are paying or getting close.",
  kpi_learning: "The learning metric that shows your biggest unknown is getting clearer.",
  sprint_goal_90_day: "The main outcome to hit in the next 90 days.",
  task_category: "The operating area this task belongs to.",
  milestones: "Major proof points with target dates, not day-to-day tasks.",
  runway_months: "How long until you run out of money or need to raise?",
  next_fundraise_trigger: "The milestone or metric that would make it worth raising more money.",
  thesis: "Why this opportunity matters and why the timing is attractive.",
  customer_notes: "Verbatim quotes and patterns from customer interviews.",
  open_questions: "Unresolved questions that still keep you up at night.",
  kill_conditions: "What would make you shut this down? Writing this now prevents moving goalposts later.",
  moat_insight: "Why you personally have an edge in building or defending this.",
  decision_log: "Timestamped pivots, commitments, and major decisions so you can audit your thinking later.",
  domain_expertise: "How much direct knowledge you have in this problem space.",
  network_access: "How easily you can reach buyers, partners, experts, or advisors in this space.",
  unfair_insight: "What you know about this market that most others do not.",
  conviction_stars: "How strongly you believe this is worth pursuing.",
  prior_startup_experience: "Your startup operating history and pattern recognition.",
  co_founder_status: "Whether the founding team is already in place.",
  capital_access: "How much funding access or runway flexibility you have today.",
  founder_statement: "In one sentence, why are you the right person to build this?",
  lois_verbal_commitments: "Number of customers who said they would pay.",
  waitlist_signups: "Number of people or companies waiting for access.",
  pilot_customers: "Number of customers actively piloting or testing.",
  revenue_to_date: "Total revenue collected so far.",
  last_customer_conversation_date: "The most recent date you spoke with a real customer.",
  signal_notes: "What you heard from the market this week."
} as const;

export type FieldTooltipKey = keyof typeof fieldTooltips;

